let n = 153;
console.log("Number is " , n);
let a = n % 10;
let m = parseInt(n/10);
let b = m % 10;
let c = parseInt(m / 10);
console.log("Last digit is" , a);
console.log("Second digit is" , b);
console.log("First digit is" , c);
console.log("Sum of digit is " , a+b+c);